import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import { QueryProvider } from "@/lib/query-client";
import { SessionWrapper } from "./SessionWrapper";
import "./globals.css";

const space_grotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Phishing awareness",
  description: "Generated by create next app with solvro config",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <QueryProvider>
        <body className={`${space_grotesk.variable} font-sans antialiased`}>
          {/*<SessionWrapper>*/}
            {children}
          {/*</SessionWrapper>*/}
        </body>
      </QueryProvider>
    </html>
  );
}