services:
  mysql:
    build:
      dockerfile: ./dockerfiles/mysql.dockerfile
      context: .
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: cisco12345
      MYSQL_DATABASE: phishing_emails
#    ports:
#      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: cisco12345
    depends_on:
      - mysql

  backend:
    build:
      dockerfile: ./dockerfiles/backend.dockerfile
      context: .
    restart: unless-stopped
    volumes:
      # don't redownload the model after every build
      - ./backend/AI_emails/models:/app/backend/AI_emails/models
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    # pass nvidia GPU if it exists
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
#
# FIXME: po skończeniu frontentu odkomentować
#  frontend:
#    build:
#      dockerfile: ./dockerfiles/frontend.dockerfile
#      context: .
#    restart: unless-stopped
#    ports:
#      - "80:3000"
#    environment:
#      NEXT_PUBLIC_API_URL: http://backend:8000
#      PORT: 3000
#    depends_on:
#      - backend
