services:
  mysql:
    build:
      dockerfile: ./dockerfiles/mysql.dockerfile
      context: .
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: cisco12345
      MYSQL_DATABASE: phishing_emails
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: cisco12345
    depends_on:
      - mysql

  backend:
    build:
      dockerfile: ./dockerfiles/backend.dockerfile
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
#
#  frontend:
#    build:
#      dockerfile: frontend.Dockerfile
#      context: .
#    ports:
#      - "80:3000"
#    depends_on:
#      - backend